---
title: "hysplit_workspace"
output: html_document
---



```{r}
library(splitr)
library(lubridate)
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library(sp)
library(raster)
library(rgdal)
library(RColorBrewer)
library(rasterVis)
```

```{r}
setwd("./hysplit")
```

```{r}
trajectory <- 
  hysplit_trajectory(
    lat = -41.83989,
    lon = 145.531014,
    height = 10,
    duration = 24,
    days = "2013-01-1",
    daily_hours = c(0, 6, 12, 18),
    direction = "backward",
    met_type = "reanalysis",
    extended_met = TRUE
  ) 
```

```{r}
trajectory_plot(trajectory)
```

```{r}
traj.series <- function (dayDate){
  trajectory <- 
    hysplit_trajectory(
      lat = -41.83989,
      lon = 145.531014,
      height = 10,
      duration = 120,
      days = dayDate,
      daily_hours = c(0, 6, 12, 18),
      direction = "backward",
      met_type = "reanalysis",
      extended_met = TRUE
  ) 
}
traj.series.250 <- function (dayDate){
  trajectory <- 
    hysplit_trajectory(
      lat = -41.83989,
      lon = 145.531014,
      height = 250,
      duration = 120,
      days = dayDate,
      daily_hours = c(0, 6, 12, 18),
      direction = "backward",
      met_type = "reanalysis",
      extended_met = TRUE
  ) 
}
traj.series.500 <- function (dayDate){
  trajectory <- 
    hysplit_trajectory(
      lat = -41.83989,
      lon = 145.531014,
      height = 500,
      duration = 120,
      days = dayDate,
      daily_hours = c(0, 6, 12, 18),
      direction = "backward",
      met_type = "reanalysis",
      extended_met = TRUE
  ) 
}
```

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

```{r}
endDate <- seq(ymd('2019-09-01'), ymd('2020-02-28'), by = '5 day')

trajL <- lapply (endDate, FUN=traj.series)
trajDF <- do.call(rbind, trajL)
latlons10.1920 <- data.frame(lon=trajDF$lon, lat=trajDF$lat)
```

```{r}
plot1920 <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons10.1920, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
```

```{r}
png("hysplit19.20.png")
print(plot1920)
dev.off()
```

```{r}
endDate <- seq(ymd('2010-09-01'), ymd('2011-02-28'), by = '5 day')

trajL2 <- lapply (endDate, FUN=traj.series)
trajDF2 <- do.call(rbind, trajL2)
latlons10.1011 <- data.frame(lon=trajDF2$lon, lat=trajDF2$lat)
```

```{r}
plot1011 <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons10.1011, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
```

```{r}
png("hysplit10.11.png")
print(plot1011)
dev.off()
```

```{r}
endDate <- seq(ymd('2006-09-01'), ymd('2007-02-28'), by = '5 day')

trajL3 <- lapply (endDate, FUN=traj.series)
trajDF3 <- do.call(rbind, trajL3)
latlons10.0607 <- data.frame(lon=trajDF3$lon, lat=trajDF3$lat)
```

```{r}
plot0607 <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons10.0607, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
```

```{r}
png("hysplit06.07.png")
print(plot0607)
dev.off()
```


```{r}
world_shp <- read_sf("coasts/ne_10m_coastline.shp")
world_outline <- as(st_geometry(world_shp), Class="Spatial")
```

```{r summarize point density by raster}

r <- raster(xmn=40, ymn=-80, xmx=160, ymx=-20, nrows=120, ncols=240)
r[] <- 0
```

```{r}
# use rasterize() to summarize the other vars from trajDF
hpa <- rasterize(latlons10.0607, r, field=trajDF3$pressure, fun=mean)

count <- rasterize(latlons10.0607, r, field=trajDF3$receptor, fun=sum)


colr <- colorRampPalette(brewer.pal(9, 'YlOrRd'))

plot(count)
plot(coastsCoarse, add=TRUE)

#try RasterVis::levelplot
```

```{r}
library(rasterVis)

colr <- colorRampPalette(brewer.pal(9, 'BuGn'))

AustProj <- CRS("+proj=aea +lat_1=-18 +lat_2=-36 +lat_0=0 +lon_0=132 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
```



```{r}
#reproject the raster:
count_Oz <- projectRaster(count, crs = AustProj)
tas_Oz <- spTransform(world_outline, CRSobj=AustProj)

#unprojected: tas, count

levelplot(count_Oz, margin=FALSE, xlab="Longitude", ylab="Latitude",  pretty=FALSE, col.regions=colr) +
  latticeExtra::layer(sp.lines(tas_Oz))


```

```{r}
colr <- colorRampPalette(brewer.pal(9, 'YlOrRd'))
count <- rasterize(latlons10.1011, r, field=trajDF2$receptor, fun=sum)
count_Oz <- projectRaster(count, crs = AustProj)
levelplot(count_Oz, margin=FALSE, xlab="Longitude", ylab="Latitude",  pretty=FALSE, col.regions=colr, at=c(5,10,20,30,40,50,75,100,150,200,250), colorkey=list(col=colr, at=c(5,10,20,30,40,50,75,100,150,200,250))) +
  latticeExtra::layer(sp.lines(tas_Oz))
```


```{r}
colr <- colorRampPalette(brewer.pal(9, 'YlOrRd'))
count <- rasterize(latlons10.1920, r, field=trajDF$receptor, fun=sum)
count_Oz <- projectRaster(count, crs = AustProj)
levelplot(count_Oz, margin=FALSE, xlab="Longitude", ylab="Latitude",  pretty=FALSE, col.regions=colr) +
  latticeExtra::layer(sp.lines(tas_Oz))
```

```{r}
endDate <- seq(ymd('2019-09-01'), ymd('2020-02-28'), by = '5 day')

trajL4 <- lapply (endDate, FUN=traj.series.250)
trajDF4 <- do.call(rbind, trajL4)
latlons250.1920 <- data.frame(lon=trajDF4$lon, lat=trajDF4$lat)
tempplot <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons250.1920, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
png("hysplit250.19.20.png")
print(tempplot)
dev.off()

trajL5 <- lapply (endDate, FUN=traj.series.500)
trajDF5 <- do.call(rbind, trajL5)
latlons500.1920 <- data.frame(lon=trajDF5$lon, lat=trajDF5$lat)
tempplot <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons500.1920, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
png("hysplit500.19.20.png")
print(tempplot)
dev.off()
```

```{r}
count <- rasterize(latlons250.1920, r, field=trajDF4$receptor, fun=sum)
count_Oz <- projectRaster(count, crs = AustProj)
levelplot(count_Oz, margin=FALSE, xlab="Longitude", ylab="Latitude",  pretty=FALSE, col.regions=colr) +
  latticeExtra::layer(sp.lines(tas_Oz))
```

```{r}
count <- rasterize(latlons500.1920, r, field=trajDF5$receptor, fun=sum)
count_Oz <- projectRaster(count, crs = AustProj)
levelplot(count_Oz, margin=FALSE, xlab="Longitude", ylab="Latitude",  pretty=FALSE, col.regions=colr) +
  latticeExtra::layer(sp.lines(tas_Oz))
```


```{r}
endDate <- seq(ymd('2010-09-01'), ymd('2011-02-28'), by = '5 day')

trajL6 <- lapply (endDate, FUN=traj.series.250)
trajDF6 <- do.call(rbind, trajL6)
latlons250.1011 <- data.frame(lon=trajDF6$lon, lat=trajDF6$lat)
tempplot <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons250.1011, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
png("hysplit250.10.11.png")
print(tempplot)
dev.off()

trajL7 <- lapply (endDate, FUN=traj.series.500)
trajDF7 <- do.call(rbind, trajL7)
latlons500.1011 <- data.frame(lon=trajDF7$lon, lat=trajDF7$lat)
tempplot <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons500.1011, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
png("hysplit500.10.11.png")
print(tempplot)
dev.off()
```

```{r}
endDate <- seq(ymd('2006-09-01'), ymd('2007-02-28'), by = '5 day')

trajL8 <- lapply (endDate, FUN=traj.series.250)
trajDF8 <- do.call(rbind, trajL8)
latlons250.0607 <- data.frame(lon=trajDF8$lon, lat=trajDF8$lat)
tempplot <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons250.0607, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
png("hysplit250.06.07.png")
print(tempplot)
dev.off()

trajL9 <- lapply (endDate, FUN=traj.series.500)
trajDF9 <- do.call(rbind, trajL9)
latlons500.0607 <- data.frame(lon=trajDF9$lon, lat=trajDF9$lat)
tempplot <- ggplot(data = world) +
    geom_sf() +
    geom_point(data = latlons500.0607, aes(x = lon, y = lat), size = 0.5, 
        shape = 1, col="grey50") +
    coord_sf(xlim = c(40, 160), ylim = c(-80, -20), expand = FALSE)
png("hysplit500.06.07.png")
print(tempplot)
dev.off()
```

```{r}
count <- rasterize(latlons10.1920, r, field=trajDF$receptor, fun=sum)
count2 <- rasterize(latlons10.1011, r, field=trajDF2$receptor, fun=sum)
```

```{r}
rbindtest <- rbind(trajDF, trajDF2, trajDF3, trajDF4, trajDF5, trajDF6, trajDF7, trajDF8, trajDF9)
latlonstest <-  data.frame(lon=rbindtest$lon, lat=rbindtest$lat)
countX <- rasterize(latlonstest, r, field=rbindtest$receptor, fun=sum)
plot(countX)
```




```{r}
countest <- count + count2

plot(countest)
```


```{r}
r <- raster(xmn=40, ymn=-80, xmx=160, ymx=-20, nrows=120, ncols=240)
r[] <- 0
endDate <- seq(ymd('1980-09-01'), ymd('1981-02-28'), by = '5 day')

trajL <- lapply (endDate, FUN=traj.series)
trajDF <- do.call(rbind, trajL)
latlons <-  data.frame(lon=trajDF$lon, lat=trajDF$lat)
countFull <- rasterize(latlons, r, field=trajDF$receptor, fun=sum)
writeRaster(countFull, "hysplit_sum_1980")
write.csv(trajDF, file = "hysplit_count_1980.csv")
```

```{r}
trajDF <- read.csv("hysplit_count_2000_2011.csv")
```



```{r}
r <- raster(xmn=40, ymn=-80, xmx=160, ymx=-20, nrows=120, ncols=240)
r[] <- 0
trajDF <- trajDF[0,] 
for (yr in c(1960:1964)){
  start <- paste0(yr,"-09-01")
  end <- paste0((yr+1),"-02-28")
  endDate <- seq(ymd(start), ymd(end), by = '5 day')
  
  trajL <- lapply(endDate, FUN=traj.series)
  trajTemp <- do.call(rbind, trajL)
  trajDF <- rbind(trajDF,trajTemp)
}

latlons <-  data.frame(lon=trajDF$lon, lat=trajDF$lat)
countFull <- rasterize(latlons, r, field=trajDF$receptor, fun=sum)
writeRaster(countFull, "hysplit_sum_1960_1964")
write.csv(trajDF, file = "hysplit_count_1960_1964.csv")
```

```{r}

df1 <- read.csv("hysplit_count_1960_1964.csv")
df2 <- read.csv("hysplit_count_1965_1969.csv")
df3 <- read.csv("hysplit_count_1970_1974.csv")
df4 <- read.csv("hysplit_count_1975_1979.csv")
df5 <- read.csv("hysplit_count_1980.csv")
df6 <- read.csv("hysplit_count_1981_1984.csv")
df7 <- read.csv("hysplit_count_1985_1989.csv")
df8 <- read.csv("hysplit_count_1990_1995.csv")
df9 <- read.csv("hysplit_count_1996_1999.csv")
df10 <- read.csv("hysplit_count_2000_2011.csv")
df11 <- read.csv("hysplit_count_2012.csv")
df12 <- read.csv("hysplit_count_2013_2018.csv")
```

```{r}
r <- raster(xmn=40, ymn=-80, xmx=180, ymx=-20, nrows=120, ncols=280)
r[] <- 0
```


```{r}
fullDF <- rbind(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)
latlons_full <-  data.frame(lon=fullDF$lon, lat=fullDF$lat)
full_trajplot <- rasterize(latlons_full, r, field=fullDF$receptor, fun=sum)
```

```{r}
plot(full_trajplot)
```

```{r}
full_trajplot
```

```{r}
levelplot(log(full_trajplot), margin=FALSE, main="Log-transformed Trajectory Count", pretty=FALSE, col.regions=colr) +
  latticeExtra::layer(sp.lines(world_outline))
```

```{r}
annual_trajplot <- full_trajplot/59
```

```{r}
colr <- colorRampPalette(brewer.pal(9, 'YlOrRd'))
png(file="logHysplit.png")
levelplot(log(annual_trajplot), margin=FALSE, main="Log-transformed Annual Trajectory Count", pretty=FALSE, col.regions=colr) +
  latticeExtra::layer(sp.lines(world_outline))
dev.off()
```


```{r}
tas_Oz <- spTransform(world_outline, CRSobj=AustProj)
colr <- colorRampPalette(brewer.pal(9, 'YlOrRd'))
```


```{r}
count_Oz <- projectRaster(full_trajplot, crs = AustProj)
levelplot(count_Oz, margin=FALSE, xlab="Longitude", ylab="Latitude",  pretty=FALSE, col.regions=colr) +
  latticeExtra::layer(sp.lines(tas_Oz))
```

```{r}
log(10)
```

```{r}
log10(10)
```

```{r}
logCount <- log(count_Oz)
levelplot(logCount, margin=FALSE, xlab="Longitude", ylab="Latitude",  pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(tas_Oz))
```

```{r}
SAMindex <- read.csv("marshallSAM.txt", header=TRUE, sep=" ")
SAMindex <- SAMindex
```

```{r}
SAMindex$SprSum <- (SAMindex$SPR + SAMindex$SUM)
```

```{r}
cor.test(SAMindex[4:62,]$SprSum, std_summary)
```

```{r}
plot(SAMindex[4:62,]$SprSum, std_summary)
```


```{r}
library(dplyr)
PosSAM <- slice_max(SAMindex, order_by = SprSum, n=12)
NegSAM <- slice_min(SAMindex, order_by = SprSum, n=12)
```

```{r}
PosSAM$X
NegSAM$X
```

```{r}
fullDF$year <- year(fullDF$traj_dt)
fullDF$month <- month(fullDF$traj_dt)
fullDF$actual_yr <- as.integer("")
```

```{r}
subYr <- subset(fullDF, month < 6)
goodYr <- subset(fullDF, month > 6)
subYr$actual_yr <- (subYr$year - 1)
goodYr$actual_yr <- goodYr$year
fullDF_splitting <- rbind(subYr, goodYr)
```

```{r}
PosSAM_traj <- fullDF_splitting[fullDF_splitting$actual_yr %in% PosSAM$X,]
NegSAM_traj <- fullDF_splitting[fullDF_splitting$actual_yr %in% NegSAM$X,]
```

```{r}
latlons_Pos <-  data.frame(lon=PosSAM_traj$lon, lat=PosSAM_traj$lat)
Pos_trajplot <- rasterize(latlons_Pos, r, field=PosSAM_traj$receptor, fun=sum)
count_Pos <- projectRaster(Pos_trajplot, crs = AustProj)

latlons_Neg <-  data.frame(lon=NegSAM_traj$lon, lat=NegSAM_traj$lat)
Neg_trajplot <- rasterize(latlons_Neg, r, field=NegSAM_traj$receptor, fun=sum)
count_Neg <- projectRaster(Neg_trajplot, crs = AustProj)
```


```{r}
logCountPos <- log(Pos_trajplot)
levelplot(logCountPos, margin=FALSE, main="SAM+ Log-transformed Trajectory Count",  pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(world_outline))
```

```{r}
annual_Pos <- Pos_trajplot/10
annual_Neg <- Neg_trajplot/10
Pos_anomaly <- annual_Pos - annual_trajplot
Neg_anomaly <- annual_Neg - annual_trajplot
```

```{r}
colr <- colorRampPalette(brewer.pal(9, 'RdBu'))
logAnomNeg <- log(Pos_anomaly)
png(file="posHysplit.png")
levelplot(Pos_anomaly, margin=FALSE, main="SAM+  Anomalies", at=c(-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9), pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(world_outline))
dev.off()
```

```{r}
png(file="negHysplit.png")
colr <- colorRampPalette(brewer.pal(9, 'RdBu'))
logAnomNeg <- log(Neg_anomaly)
levelplot(Neg_anomaly, margin=FALSE, main="SAM- Anomalies", at=c(-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9), pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(world_outline))
dev.off()
```



```{r}
logCountNeg <- log(Neg_trajplot)
levelplot(logCountNeg, margin=FALSE, main="SAM- Log-transformed Trajectory Count",  pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(world_outline))
```

O18 compositing
Highest O18: 1967 2018 2015 2017 1963 2007 1965 2004 1997 2014 1987 2016 2003 1980 1998
Lowest O18: 1970 1984 1985 1968 1973 1971 1993 2009 1975 2011 1991 1990 1996 2001 1960

```{r}
Poso18_traj <- fullDF_splitting[fullDF_splitting$actual_yr %in% Poso18,]
Nego18_traj <- fullDF_splitting[fullDF_splitting$actual_yr %in% Nego18,]
```


```{r}
latlons_Pos <-  data.frame(lon=Poso18_traj$lon, lat=Poso18_traj$lat)
Pos_trajplot <- rasterize(latlons_Pos, r, field=Poso18_traj$receptor, fun=sum)
count_Pos <- projectRaster(Pos_trajplot, crs = AustProj)

latlons_Neg <-  data.frame(lon=Nego18_traj$lon, lat=Nego18_traj$lat)
Neg_trajplot <- rasterize(latlons_Neg, r, field=Nego18_traj$receptor, fun=sum)
count_Neg <- projectRaster(Neg_trajplot, crs = AustProj)
```

```{r}
annual_Pos <- Pos_trajplot/15
annual_Neg <- Neg_trajplot/15
Pos_anomaly <- annual_Pos - annual_trajplot
Neg_anomaly <- annual_Neg - annual_trajplot
```


```{r}
colr <- colorRampPalette(brewer.pal(9, 'RdBu'))

logAnomPos <- log(Pos_anomaly)
levelplot(Pos_anomaly, margin=FALSE, main="Top 25% δ18O Anomalies",  at=c(-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12), pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(world_outline))

```
png(filename="hysplit_lowO18_anom.png", height=700, width=1200)


```{r}
colr <- colorRampPalette(brewer.pal(9, 'RdBu'))

logAnomNeg <- log(Neg_anomaly)
levelplot(Neg_anomaly, margin=FALSE, main="Bottom 25% δ18O Anomalies", at=c(-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12), pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(world_outline))

```


GNIP compositing
Highest GNIP: 97 88 83 87 02 89
Lowest GNIP: 86 96 90 79 84 99

```{r}
Posgnip_traj <- fullDF_splitting[fullDF_splitting$actual_yr %in% Posgnip$seas.year,]
Neggnip_traj <- fullDF_splitting[fullDF_splitting$actual_yr %in% Neggnip$seas.year,]
```


```{r}
latlons_Pos <-  data.frame(lon=Posgnip_traj$lon, lat=Posgnip_traj$lat)
Pos_trajplot <- rasterize(latlons_Pos, r, field=Posgnip_traj$receptor, fun=sum)
count_Pos <- projectRaster(Pos_trajplot, crs = AustProj)

latlons_Neg <-  data.frame(lon=Neggnip_traj$lon, lat=Neggnip_traj$lat)
Neg_trajplot <- rasterize(latlons_Neg, r, field=Neggnip_traj$receptor, fun=sum)
count_Neg <- projectRaster(Neg_trajplot, crs = AustProj)
```

```{r}
annual_Pos <- Pos_trajplot/6
annual_Neg <- Neg_trajplot/6
Pos_anomaly <- annual_Pos - annual_trajplot
Neg_anomaly <- annual_Neg - annual_trajplot
```

```{r}
Neg_anomaly
```


```{r}
colr <- colorRampPalette(brewer.pal(9, 'RdBu'))

logAnomPos <- log(Pos_anomaly)
levelplot(Pos_anomaly, margin=FALSE, main="Top 25% GNIP Anomalies",  at=c(-26,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,26), pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(world_outline))
```







```{r}
colr <- colorRampPalette(brewer.pal(9, 'RdBu'))

logAnomPos <- log(Neg_anomaly)
levelplot(Neg_anomaly, margin=FALSE, main="Bottom 25% GNIP Anomalies",  at=c(-26,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,26), pretty=FALSE, col.regions=colr, colorkey=list(col=colr)) +
  latticeExtra::layer(sp.lines(world_outline))

```





